-- Full Database Schema
-- Generated by Antigravity
-- Combined from multiple migration files

-- ==========================================
-- 1. Base Schema (supabase_schema.sql)
-- ==========================================

-- Create profiles table
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  phone text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create cars table
create table public.cars (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  price numeric not null,
  governorate text not null,
  brand text not null,
  year int not null,
  transmission text not null, -- 'automatic', 'manual'
  fuel_type text not null, -- 'petrol', 'diesel', 'electric', 'hybrid'
  description text,
  images text[] default '{}',
  is_premium boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.cars enable row level security;

-- Profiles policies
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Cars policies
create policy "Cars are viewable by everyone."
  on public.cars for select
  using ( true );

create policy "Users can insert their own cars."
  on public.cars for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own cars."
  on public.cars for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own cars."
  on public.cars for delete
  using ( auth.uid() = user_id );

-- Storage bucket for car images
insert into storage.buckets (id, name, public)
values ('cars', 'cars', true)
on conflict (id) do nothing;

create policy "Anyone can view car images"
  on storage.objects for select
  using ( bucket_id = 'cars' );

create policy "Authenticated users can upload car images"
  on storage.objects for insert
  with check ( bucket_id = 'cars' and auth.role() = 'authenticated' );

create policy "Users can update their own car images"
  on storage.objects for update
  using ( bucket_id = 'cars' and auth.uid() = owner );

create policy "Users can delete their own car images"
  on storage.objects for delete
  using ( bucket_id = 'cars' and auth.uid() = owner );

-- ==========================================
-- 2. Phase 3 Migration (Missing)
-- ==========================================
-- Note: phase3_migration.sql could not be read. 
-- Please verify if any critical tables (e.g. notifications) are missing.
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS address text;
 ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS date_of_birth date;
 ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS currency text DEFAULT 'IQD';

-- ==========================================
-- 3. Phase 4 Migration (phase4_migration.sql)
-- ==========================================

-- Create settings table
create table public.settings (
  key text primary key,
  value text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert initial exchange rate
insert into public.settings (key, value)
values ('exchange_rate', '1530')
on conflict (key) do update set value = excluded.value;

-- Add avatar_url to profiles
alter table public.profiles add column if not exists avatar_url text;

-- Enable RLS for settings
alter table public.settings enable row level security;

-- Settings policies
create policy "Settings are viewable by everyone."
  on public.settings for select
  using ( true );

create policy "Only admins can update settings."
  on public.settings for update
  using ( (select role from public.profiles where id = auth.uid()) = 'admin' );

-- ==========================================
-- 4. Premium Migration (premium_migration.sql)
-- ==========================================

-- Create premium_requests table
create table public.premium_requests (
  id uuid default gen_random_uuid() primary key,
  car_id uuid references public.cars(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  receipt_url text not null,
  status text default 'pending', -- pending, approved, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.premium_requests enable row level security;

-- Policies for premium_requests
create policy "Users can view their own requests"
  on public.premium_requests for select
  using ( auth.uid() = user_id );

create policy "Users can create requests"
  on public.premium_requests for insert
  with check ( auth.uid() = user_id );

create policy "Admins can view all requests"
  on public.premium_requests for select
  using ( exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') );

create policy "Admins can update requests"
  on public.premium_requests for update
  using ( exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') );

-- Create storage bucket for receipts if not exists
insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', true)
on conflict (id) do nothing;

-- Storage policies for receipts
create policy "Authenticated users can upload receipts"
  on storage.objects for insert
  with check ( bucket_id = 'receipts' and auth.role() = 'authenticated' );

create policy "Users can view their own receipts"
  on storage.objects for select
  using ( bucket_id = 'receipts' and auth.uid() = owner );

create policy "Admins can view all receipts"
  on storage.objects for select
  using ( bucket_id = 'receipts' and exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') );

-- ==========================================
-- 5. Page Views Migration (page_views_migration.sql)
-- ==========================================

-- Create table for tracking page views
create table public.page_views (
  id uuid default gen_random_uuid() primary key,
  visitor_id uuid default auth.uid(), -- Optional: track logged-in users
  path text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.page_views enable row level security;

-- Policies
create policy "Anyone can insert page views"
  on public.page_views for insert
  with check ( true );

create policy "Admins can view page views"
  on public.page_views for select
  using ( exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') );

-- Create a function to get visitor stats (Initial version)
create or replace function get_visitor_stats()
returns table (
  current_online bigint,
  weekly_visits bigint,
  monthly_visits bigint
)
language plpgsql
security definer
as $$
begin
  return query
  select 
    (select count(distinct visitor_id) from public.page_views where created_at > now() - interval '15 minutes') as current_online,
    (select count(*) from public.page_views where created_at > now() - interval '7 days') as weekly_visits,
    (select count(*) from public.page_views where created_at > now() - interval '30 days') as monthly_visits;
end;
$$;

-- ==========================================
-- 6. Page Views Upgrade (page_views_upgrade.sql)
-- ==========================================

-- 1. Create a function to get chart data for revenue
create or replace function get_financial_chart_data()
returns table (
  date text,
  revenue bigint
)
language plpgsql
security definer
as $$
begin
  return query
  select 
    to_char(created_at, 'YYYY-MM-DD') as date,
    count(*) * 5000 as revenue -- Assuming 5000 IQD per approved request
  from public.premium_requests
  where status = 'approved'
  and created_at > now() - interval '30 days'
  group by 1
  order by 1;
end;
$$;

-- 2. Update get_visitor_stats to be more accurate (Count DISTINCT visitor_id)
create or replace function get_visitor_stats()
returns table (
  current_online bigint,
  weekly_visits bigint,
  monthly_visits bigint
)
language plpgsql
security definer
as $$
begin
  return query
  select 
    -- Online: Unique visitors in last 15 mins
    (select count(distinct visitor_id) from public.page_views where created_at > now() - interval '15 minutes') as current_online,
    -- Weekly: Unique visitors in last 7 days
    (select count(distinct visitor_id) from public.page_views where created_at > now() - interval '7 days') as weekly_visits,
    -- Monthly: Unique visitors in last 30 days
    (select count(distinct visitor_id) from public.page_views where created_at > now() - interval '30 days') as monthly_visits;
end;
$$;

-- ==========================================
-- 7. Update Admin Phone (update_admin_phone_setting.sql)
-- ==========================================

-- Add admin_phone to settings
insert into public.settings (key, value)
values ('admin_phone', '07800000000')
on conflict (key) do nothing;

-- ==========================================
-- 8. Fix Cars Admin RLS (fix_cars_admin_rls.sql)
-- ==========================================

-- FIX RLS Policies for cars table to allow admins to manage everything
DROP POLICY IF EXISTS "Admins can update any car" ON cars;
DROP POLICY IF EXISTS "Admins can delete any car" ON cars;

-- Allow admins to update any car
CREATE POLICY "Admins can update any car" ON "public"."cars"
FOR UPDATE 
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Allow admins to delete any car
CREATE POLICY "Admins can delete any car" ON "public"."cars"
FOR DELETE 
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- ==========================================
-- 9. Fix Settings RLS (fix_settings_rls.sql)
-- ==========================================

-- FIX RLS Policies for settings table
DROP POLICY IF EXISTS "Public read access for settings" ON settings;
DROP POLICY IF EXISTS "Admins can update settings" ON settings;

-- Allow everyone to read settings (required for currency conversion globally)
CREATE POLICY "Enable read access for all users" ON "public"."settings"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- Allow admins to manage settings (using role check in profiles table)
CREATE POLICY "Enable all access for admins only" ON "public"."settings"
AS PERMISSIVE FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Enable RLS
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 10. Fix Profiles Admin RLS (fix_profiles_admin_rls.sql)
-- ==========================================

-- FIX RLS Policies for profiles table to allow admins to manage users
DROP POLICY IF EXISTS "Admins can update any profile" ON profiles;
DROP POLICY IF EXISTS "Admins can delete any profile" ON profiles;

-- Allow admins to update any profile
CREATE POLICY "Admins can update any profile" ON "public"."profiles"
FOR UPDATE 
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Allow admins to delete any profile
CREATE POLICY "Admins can delete any profile" ON "public"."profiles"
FOR DELETE 
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- ==========================================
-- 11. Enable Realtime (enable_realtime.sql)
-- ==========================================

-- Enable Realtime for specific tables
begin;
  -- Remove if already exists to avoid error or duplication
  drop publication if exists supabase_realtime;

  -- Create publication for realtime
  create publication supabase_realtime for table 
    public.premium_requests, 
    public.page_views, 
    public.profiles,
    public.cars; -- Added cars for realtime home page
commit;
